# Weather Dataset

## Inspect

In [1]:
import pandas as pd
df = pd.read_csv("weather_stream_v2.csv")

In [2]:
print("Shape:")
print(df.shape)
print("Columns:")
print(df.columns.tolist())
print("Data types:")
print(df.dtypes)
print("First 5 rows:")
print(df.head())

Shape:
(50000, 17)

Columns:
['household_id', 'weather_region', 'weather_city', 'weather_station', 'climate_zone', 'condition_type', 'temperature_celsius', 'humidity_percent', 'wind_speed_kmh', 'rainfall_mm', 'pressure_hpa', 'solar_radiation', 'dew_point', 'uv_index', 'visibility_km', 'cloud_cover_percent', 'timestamp']

Data types:
household_id             int64
weather_region          object
weather_city            object
weather_station         object
climate_zone            object
condition_type          object
temperature_celsius    float64
humidity_percent       float64
wind_speed_kmh         float64
rainfall_mm            float64
pressure_hpa           float64
solar_radiation        float64
dew_point              float64
uv_index               float64
visibility_km          float64
cloud_cover_percent    float64
timestamp               object
dtype: object

First 5 rows:
   household_id weather_region weather_city weather_station climate_zone  \
0          8270          North      Chennai            WS03          Dry
1          1860          North    Bangalore            WS01     Tropical
2          6390          North       Mumbai            WS02     Tropical
3          6191          South        Delhi            WS02    Temperate
4          6734           East      Chennai            WS01    Temperate

  condition_type  temperature_celsius  humidity_percent  wind_speed_kmh  \
0        Cloudy%            15.396439         83.027893       19.599233
1         Rainy%            24.928979         59.170045        1.947492
2         Sunny%            19.568021         26.325728        8.389250
3         Rainy%            20.180258         66.339227       10.672130
4        Cloudy%            23.712156         30.247075       10.518948

   rainfall_mm  pressure_hpa  solar_radiation  dew_point   uv_index  \
0     0.215141   1011.472876       773.686423  10.120133   8.203110
1     3.553745    988.527263       126.660112  16.144860   9.151022
2    30.100179   1009.302689       611.739722  18.923295   2.233362
3    28.581839    988.024861       527.308590  12.558739  11.787065
4    48.418401   1000.547447       171.130629  22.693518   2.510706

   visibility_km  cloud_cover_percent   timestamp
0       1.950419            81.886521  30-08-2023
1       3.364005             8.284568  04-12-2023
2       4.012448            40.530773  16-10-2023
3       5.628186             5.086902  09-08-2023
4       5.305352            19.668789  28-08-2023

## Check Missing Values & Duplicate Rows

In [3]:
print("Missing values:")
print(df.isnull().sum())
print("Duplicate rows:")
print(df.duplicated().sum())
print("DateTime info (first and last):")
print(df.iloc[0, 0], "to", df.iloc[-1, 0])

Missing values:
household_id              0
weather_region            0
weather_city              0
weather_station           0
climate_zone              0
condition_type            0
temperature_celsius    1000
humidity_percent       1000
wind_speed_kmh         1000
rainfall_mm            1000
pressure_hpa           1000
solar_radiation        1000
dew_point              1000
uv_index               1000
visibility_km          1000
cloud_cover_percent    1000
timestamp                 0
dtype: int64

Duplicate rows:
0

DateTime info (first and last):
8270 to 8309

## Check Unique Values

In [4]:
df.nunique()

household_id            8964
weather_region             4
weather_city               4
weather_station            3
climate_zone               3
condition_type             3
temperature_celsius    49000
humidity_percent       49000
wind_speed_kmh         49000
rainfall_mm            48998
pressure_hpa           48991
solar_radiation        49000
dew_point              49000
uv_index               49000
visibility_km          49000
cloud_cover_percent    49000
timestamp                365
dtype: int64

## Understand

In [7]:
df[df['temperature_celsius'].isnull()].head()

,household_id,weather_region,weather_city,weather_station,climate_zone,condition_type,temperature_celsius,humidity_percent,wind_speed_kmh,rainfall_mm,pressure_hpa,solar_radiation,dew_point,uv_index,visibility_km,cloud_cover_percent,timestamp
54,4843,South,Bangalore,WS03,Dry,Cloudy%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26-12-2023
115,8858,East,Delhi,WS01,Dry,Cloudy%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30-08-2023
148,1663,South,Bangalore,WS02,Temperate,Cloudy%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23-06-2023
178,5218,West,Mumbai,WS03,Dry,Rainy%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26-09-2023
238,5973,West,Chennai,WS02,Temperate,Cloudy%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27-08-2023

In [8]:
df[df['temperature_celsius'].isnull()]['household_id'].nunique()

943

In [9]:
df[df['temperature_celsius'].isnull()]['timestamp'].value_counts().head(10)

timestamp
08-10-2023    10
09-07-2023     9
19-09-2023     8
16-10-2023     7
16-04-2023     7
30-09-2023     7
22-12-2023     7
18-07-2023     7
17-04-2023     7
09-08-2023     7
Name: count, dtype: int64

## Clean

In [10]:
df = df.dropna(subset=['temperature_celsius'])

In [11]:
df.isnull().sum()

household_id           0
weather_region         0
weather_city           0
weather_station        0
climate_zone           0
condition_type         0
temperature_celsius    0
humidity_percent       0
wind_speed_kmh         0
rainfall_mm            0
pressure_hpa           0
solar_radiation        0
dew_point              0
uv_index               0
visibility_km          0
cloud_cover_percent    0
timestamp              0
dtype: int64

In [12]:
df.shape

(49000, 17)

In [13]:
df['condition_type'].unique()

array(['Cloudy%', 'Rainy%', 'Sunny%'], dtype=object)

In [14]:
df['condition_type'] = df['condition_type'].str.rstrip('%')

In [15]:
df['condition_type'].unique()

array(['Cloudy', 'Rainy', 'Sunny'], dtype=object)

In [16]:
df['timestamp'].head()

0    30-08-2023
1    04-12-2023
2    16-10-2023
3    09-08-2023
4    28-08-2023
Name: timestamp, dtype: object

In [17]:
df.dtypes['timestamp']

dtype('O')

In [18]:
df['timestamp'] = pd.to_datetime(df['timestamp'], format='%d-%m-%Y')

In [20]:
df['timestamp'].min(), df['timestamp'].max()

(Timestamp('2023-01-01 00:00:00'), Timestamp('2023-12-31 00:00:00'))

In [21]:
df.describe()

,household_id,temperature_celsius,humidity_percent,wind_speed_kmh,rainfall_mm,pressure_hpa,solar_radiation,dew_point,uv_index,visibility_km,cloud_cover_percent,timestamp
count,49000.000000,49000.000000,49000.000000,49000.000000,49000.000000,49000.000000,49000.000000,49000.000000,49000.000000,49000.000000,49000.000000,49000
mean,5495.806000,27.538076,55.005900,19.969839,24.834292,1015.063548,550.568698,17.538265,6.507041,5.507916,50.046207,2023-07-01 08:37:32.865305856
min,1000.000000,15.001710,20.000521,0.000284,0.000401,980.000804,100.002056,10.000106,1.000160,1.000154,0.003579,2023-01-01 00:00:00
25%,3235.750000,21.345862,37.507431,10.071168,12.348714,997.553299,325.621458,13.781932,3.760592,3.255098,24.879839,2023-04-01 00:00:00
50%,5501.000000,27.522791,55.140698,19.892803,24.743282,1015.139203,548.987168,17.588742,6.514526,5.523199,50.171530,2023-07-01 00:00:00
75%,7746.000000,33.807649,72.505575,29.903910,37.309747,1032.477443,775.990334,21.297286,9.267222,7.750266,74.987093,2023-10-02 00:00:00
max,9999.000000,39.999854,89.999013,39.998874,49.999719,1049.998766,999.964932,24.999408,11.999731,9.999627,99.999105,2023-12-31 00:00:00
std,2601.082076,7.207960,20.198259,11.514593,14.409901,20.210992,259.604092,4.324863,3.180774,2.600280,28.882987,NaN

## Final Validation

In [22]:
df.shape

(49000, 17)

In [23]:
df.isnull().sum().sum()

np.int64(0)

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.dtypes

household_id                    int64
weather_region                 object
weather_city                   object
weather_station                object
climate_zone                   object
condition_type                 object
temperature_celsius           float64
humidity_percent              float64
wind_speed_kmh                float64
rainfall_mm                   float64
pressure_hpa                  float64
solar_radiation               float64
dew_point                     float64
uv_index                      float64
visibility_km                 float64
cloud_cover_percent           float64
timestamp              datetime64[ns]
dtype: object

In [27]:
df.to_csv(r'C:\Users\Royal\Downloads\weather_data_cleaned.csv', index=False)